/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-container": "#c0ceff",
        "outline-variant": "#c0c8cd",
        "on-tertiary-fixed-variant": "#2a4386",
        "secondary-fixed-dim": "#ffbb1e",
        "secondary-container": "#fcb812",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#236580",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "surface-bright": "#f8f9fa",
        "on-tertiary-fixed": "#00174a",
        secondary: "#7c5800",
        "primary-fixed-dim": "#92cfee",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e1e3e4",
        background: "#f8f9fa",
        "secondary-fixed": "#ffdea7",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-primary-container": "#9bd7f7",
        "primary-fixed": "#c0e8ff",
        "surface-container": "#edeeef",
        "on-surface-variant": "#40484d",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-fixed": "#271900",
        "inverse-primary": "#92cfee",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed": "#001e2b",
        "on-secondary-fixed-variant": "#5e4200",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004d66",
        "tertiary-fixed-dim": "#b3c5ff",
        "primary-container": "#1a5f7a",
        "surface-dim": "#d9dadb",
        tertiary: "#233d80",
        "tertiary-container": "#3d5599",
        outline: "#70787d",
        "tertiary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        primary: "#00475e",
        "on-secondary-container": "#6a4b00",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
